name: rongcloud_im_plugin_example
description: Demonstrates how to use the rongcloud_im_plugin plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4
  file_picker: ^4.0.2
  open_file: ^3.2.1
  #flutter_audio_recorder: ^0.5.5
  path_provider: ^2.0.3
  permission_handler: ^8.1.4+2
  flutter_sound: ^8.3.10
  flutter_local_notifications: ^8.1.1+2
  camera: ^0.9.2+2
  video_player: ^2.1.15
  percent_indicator: ^3.0.1
  fluttertoast: ^8.0.8
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  flutter_webview_plugin: ^0.4.0
  webview_flutter: ^2.0.12
  image_gallery_saver: ^1.6.9
  url_launcher: ^6.0.10
  rxdart: ^0.27.2
  flutter_cache_manager: ^3.1.2
  connectivity: ^3.0.6
  ffi: ^1.1.2
  flutter_plugin_record: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  rongcloud_im_plugin:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/RCFlutterConf.json
    - assets/images/
    - assets/combine.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages